### ISSUE TITLE
helpers for including sprites in other css classes

### ISSUE THREAD

**Issue by hitmands** [Code-Y/postcss-cyspriter#10]
Could be nice to have a method that allows the ability to include a sprite in other selectors.

Considering a simple case:

``` css
.my-class {
   cy-include: 'icons-foo';
}
```

A nice result could be:

``` css
.icons,
.icons-foo,
.my-class {
   ...
}
```
