### ISSUE TITLE
Improve retina support

### ISSUE THREAD

**Issue by lughino** [Code-Y/postcss-cyspriter#11]
At present support to the retina performs only the creation of sprites retina compatible.

Create a system that gives the possibility to create two different sprites for a retina and a normal, and create the correct media queries.

Media queries example:

``` css
/* CSS for devices with normal screens */
.icons {
    background-image: url(icon-sprite.png);
    background-repeat: no-repeat;
}

/* CSS for high-resolution devices */
@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
only screen and (-moz-min-device-pixel-ratio: 1.5),
only screen and (-o-min-device-pixel-ratio: 3/2),
only screen and (min-device-pixel-ratio: 1.5) {
    .icons {
        background-image: url(icon-sprite-2x.png);
        background-size: 200px 100px;
        background-repeat: no-repeat;
    }
}
```
